# Generated by Django 6.0.2 on 2026-03-06 16:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('action', models.CharField(max_length=30, verbose_name='Action')),
                ('entity_type', models.CharField(max_length=100, verbose_name='Entity Type')),
                ('entity_id', models.UUIDField(blank=True, null=True, verbose_name='Entity Id')),
                ('user_id', models.UUIDField(blank=True, null=True, verbose_name='User Id')),
                ('user_name', models.CharField(blank=True, max_length=255, verbose_name='User Name')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Ip Address')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Details')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
            options={
                'db_table': 'audit_log_auditentry',
                'abstract': False,
            },
        ),
    ]
